# Generated by Django 4.1.2 on 2023-01-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_carts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('in-cart', 'in-cart'), ('cancelled', 'cancelled')], default='in-cart', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('dispatched', 'dispatched'), ('in-transit', 'in-transit'), ('cancelled', 'cancelled')], default='order-placed', max_length=200),
        ),
    ]
